### ISSUE TITLE
"MainWindow" stays open on startup / autostart Fedora KDE

### ISSUE THREAD

**Issue by citizenserious** [Hypfer/valetudo-tray-companion#3]
![image](https://github.com/user-attachments/assets/046674ce-7a0a-4b1d-8dbb-cb8d472e9958)

When I close the window the tray closes too. When I manually start it after startup (also when starting over the autostart menu) this "MainWindow" appears for a short time but then closes itself.

I am on Fedora 40 KDE. 
This could also be an issue of my system or X11 I do not know.

It also shows me this in both cases:
![image](https://github.com/user-attachments/assets/b99edda0-5880-430c-b7f8-9d953cf20ece)

**Comment by Hypfer** [comment]
I have the same thing happening on some reboots on debian 12 with KDE on X11.

Definitely unrelated to this code though. Most likely an issue in avalonia, though to be fair to it, this project currently uses a 2 year old preview version of it https://github.com/Hypfer/valetudo-tray-companion/blob/9995268415c8d4ae4d2845b7eb0846d73a018e05/valetudo-tray-companion/valetudo-tray-companion.csproj#L23

Maybe a version bump is all it takes

**Comment by Hypfer** [comment]
https://github.com/Hypfer/valetudo-tray-companion/releases/tag/2024.08.0
